feat: 회원 관련 로직 구현
ClapPause/backend pull request #13
Opened 2024-08-10 09:52 UTC by yunjunghun0116

## 구현 사항
1. 회원가입 기능
2. 로그인 기능

2024-08-10 10:05 UTC, boyunee requested changes
수고하셨습니다~ 일부 사항 코멘트 남겼습니다!

2024-08-10 10:05 UTC, boyunee commented on src/main/java/com/clap/pause/dto/auth/RegisterRequest.java
> +        String profileImage,
profile image 를 request에서 받기 보다는 나중에 member 객체 생성할 때 기본이미지를 넣는게 어떨까요?? 왜냐면 회원가입 플로우에서 사용자가 처음부터 프로필 이미지를 넣기보다는 기본으로 설정하고 나중에 마이 페이지에서 직접 바꾸는 플로우로 될것같아서요!

2024-08-13 08:57 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/auth/AuthService.java
> +        var encodedPassword = passwordEncoder.encode(registerRequest.password());
빈으로 등록된 PasswordEncoder가 RegisterRequest에 담긴 password를 암호화하는 기능을 합니다!

2024-08-13 08:57 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/dto/auth/RegisterRequest.java
> +        String profileImage,
네! 해당 의견 반영하였습니다!

2024-08-13 09:35 UTC, boyunee approved these changes
수고하셨습니다! 
의견이 하나 있는데, 앞으로 service단에 메소드들은 주석을 달아서 이해하기 쉽게 하는게 어떨까요??
![image](https://github.com/user-attachments/assets/3c0977f3-ad7e-4c90-8659-e38c614bff87)

이렇게요! 그리고 코드 작성 중 중간중간 간단히 주석으로 설명하는 게 좋을 것같아요! 좀 귀찮겠지만 그렇게 하면 코드리뷰가 훨씬 빨라지더라구요 ㅎㅎ

2024-08-13 17:16 UTC, clap-pause approved these changes

2024-08-13 17:16 UTC, merged