feat : 투표하기 , 재투표하기, 투표조회하기
ClapPause/backend pull request #27
Opened 2024-09-19 05:09 UTC by boyunee

2024-09-20 07:58 UTC, yunjunghun0116 approved these changes
잘 작성하고 Image도 String으로 전부 바꾸셨네용! 굿굿

2024-09-20 08:05 UTC, yunjunghun0116 requested changes
Service 계층에서 var 와 같은 타입추론 방식과 타입명시 방식의 충돌이 자주 발생해서 하나로 통일해주세요!
제가 제안한 방식에 대해서 바로 적용하기보다는 한번 더 회의를 거치고 정하면 그 후에 적용하는 게 좋을 것 같은데, 한번 생각만 해봐주세요 :)

크게 로직상 문제가 있어보이는 부분도 없고 잘 작성해주셨네요!!

2024-09-20 08:05 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/dto/post/response/PostListResponse.java
> +    public static PostListResponse of(Long id, Long departmentGroupId, String title, String contents, PostCategory postCategory, PostType postType, LocalDateTime createdAt, String memberName, String
제안해보는것인데 이 부분을
```
public static PostListResponse of(
Long id, 
Long departmentGroupId, 
String title, 
String contents, 
PostCategory 
postCategory, 
PostType postType, 
LocalDateTime createdAt, 
String memberName, 
String university, 
String department, 
List<String> images, 
List<TextVoteOptionResponse> textVoteOptionResponses, 
List<ImageVoteOptionResponse> imageVoteOptionResponses
){~}
```
뿐만 아니라 나머지 of메서드, 생성자도 아래로 내리는것으로 통일해보는것 어때요?

제가 기존에 한줄로 길게 써보자고 제안을 했었는데, 너무 길어지니까 오히려 가독성을 해치는 것 같아서 차라리 좀 길어지더라도 아래로 내리는게 나을수도 있겠다는 생각이 드네요!
이렇게 되면 생성자, 객체 생성 등에서 일부 공사 작업이 필요할 수 있지만 가독성 측면에서는 충분히 가져갈 수 있는 방법이라고 생각이 됩니다!

2024-09-20 08:05 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/ImageVoteHistoryService.java
> +        List<ImageVoteHistory> imageVoteHistories = imageVoteHistoryRepository.findAllByMember(member);
var로 수정하는게 좋을 것 같아요 통일성 측면에서!

2024-09-20 08:05 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/ImageVoteHistoryService.java
> +        ImageVoteHistory imageVoteHistory = findImageVoteHistoryByPostId(imageVoteHistories, postId);
이부분도요!

2024-09-20 08:05 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/ImageVoteHistoryService.java
> +        Long count = imageVoteHistoryRepository.countByImageVoteOption(ImageVoteOption);
이부분도요!

2024-09-23 07:56 UTC, boyunee commented on src/main/java/com/clap/pause/dto/post/response/PostListResponse.java
> +    public static PostListResponse of(Long id, Long departmentGroupId, String title, String contents, PostCategory postCategory, PostType postType, LocalDateTime createdAt, String memberName, String
좋은 것 같아요! 그럼 of메소드 정의할 땐 길게 쓰고 of 메소드를 사용할 때만 한 줄 씩 내리는 게 어떄요? 정의할 땐 모든 필드를 사용한다는걸 알고있고 또 바로 윗줄에 record 필드가 있으니깐 한줄로 쓸 필욘 없을것같아서요!

2024-09-23 09:18 UTC, merged