feat: 댓글 좋아요 도메인 로직 처리
ClapPause/backend pull request #30
Opened 2024-09-28 09:44 UTC by yunjunghun0116

## 작업 내용

- 댓글 좋아요 기능
- 댓글 좋아요 취소 기능
- 댓글 조회 시 총 댓글 좋아요 수 확인 기능

2024-09-28 11:57 UTC, boyunee requested changes
수고하셨습니다! querydsl 쓰셔서 잘하신것같아요!

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/service/CommentLikeService.java
> +        commentLikeRepository.deleteAllByCommentIdAndMemberId(commentId, memberId);
ㅇ

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/controller/CommentLikeController.java
> +        return ResponseEntity.ok()
댓글 좋아요를 누르면 빨간 하트로 바껴야되니까 responseentity.created로 해서 연결요청하도록 해야되지않을까요!?

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/repository/custom/CommentLikeCustomRepositoryImpl.java
> +                .where(commentLike.comment.post.id.eq(postId))
post 엔티티로 먼저 postId가 유효한지 검사하고 where(commentLike.comment.post.eq(post)) 이렇게 하는게 에러를 더 잡을 수 있지않을까요!? 고민해보셨으면 좋겠습니다

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/service/CommentLikeService.java
> +    }
comment와 member를 가져올 거면 existsByCommentAndMember로 써도 될것같아요! 그리고 거의 모든 jpa 메소드에 ~By~Id로 하신것같은데요! 찾아보니 그렇게 하면 의도치 않게 left outer join이 발생한다고 합니다 https://bcp0109.tistory.com/305

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/service/CommentLikeService.java
> +        var commentLikeQueryResults = commentLikeRepository.getCommentLikeQueryResults(postId);
요기서 post로 찾는거 어떤가요? postId가존재하지 않거나  삭제된거일 수 도있으니깐요!

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/model/Comment.java
> +        if (!this.post.getId().equals(postId)) {
여기서로 post를 찾고 나선 this.post.equals(post) 로 더욱 간결해질 것 같아요 ㅎㅎ

2024-09-28 11:57 UTC, boyunee commented on src/main/java/com/clap/pause/service/image/PostImageService.java
> +import java.util.List;
import 문의 자리 차이로 커밋이 보내지네요 ㅠㅠ 이렇게 파일이 자주 바꿔 체크할 파일이 많아지니 좀 불편하네요 다음에 왜 그런지 같이 한번 알아보아요

2024-10-01 08:02 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/controller/CommentLikeController.java
> +        return ResponseEntity.ok()
댓글 좋아요가 수행될 경우 클라이언트는 200 일 경우 화면을 다시 렌더링해줄 필요 없이 해당 컨테이너(댓글의 정보를 담고있음)의 isLike 의 변수를 false -> true 로 변경만 해주면 되기 때문에 created이 아닌 ok 로 보내도록 하였습니다!

2024-10-01 09:45 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/CommentLikeService.java
> +    }
녱,,!

2024-10-01 09:53 UTC, yunjunghun0116 commented on src/main/java/com/clap/pause/service/image/PostImageService.java
> +import java.util.List;
이부분에 대해서는 저희 둘이 코드 스타일을 통일 했기 때문에 앞으로는 발생하지 않을 문제라고 생각합니다!

2024-10-01 09:59 UTC, boyunee approved these changes

2024-10-01 10:01 UTC, merged